import {
  Employee,
  Department,
  Position,
  Skill,
  Project,
  Training,
  Goal,
  PerformanceReview,
  Feedback,
  LeaveRequest,
  LeaveType,
  LeaveBalance,
  Attendance,
  AttendanceSummary,
  Notification,
  AnalyticsOverview,
  PerformanceTrend,
  DashboardData,
  LeaveRequestStatus,
  AttendanceStatus,
  ProjectStatus,
  TrainingStatus,
  TrainingType,
  GoalStatus,
  PerformanceReviewStatus,
  Achievement,
  AchievementType,
  MentoringRelationship,
  MentoringStatus,
  SkillType,
  SkillCategory,
  SkillLevel,
  EmployeeProfile,
  PolicyDocument,
  PolicyAcknowledgment,
  PolicyStatus,
  PolicyCategory,
  Payroll,
  PayrollStatus,
  Separation,
  SeparationStatus,
  SeparationType,
  Contractor,
  ContractLabor,
  ContractLaborStatus,
  ContractLaborAttendance,
  ServiceRequest,
  ServiceRequestStatus,
  ServiceRequestPriority,
  ServiceProposal,
  ProposalStatus,
  ServiceBooking,
  BookingStatus,
} from '../types';
import { ProjectAllocation, AllocationStatus } from '../types/allocation';

const generateId = () => Math.random().toString(36).substring(2, 15);

const mockDepartments: Department[] = [
  { id: '1', name: 'Tecnologia da Informação', description: 'Departamento de TI', costCenter: 'TI-001', createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: '2', name: 'Recursos Humanos', description: 'Departamento de RH', costCenter: 'RH-002', createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: '3', name: 'Vendas', description: 'Departamento de Vendas', costCenter: 'VEND-003', createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: '4', name: 'Marketing', description: 'Departamento de Marketing', costCenter: 'MKT-004', createdAt: '2024-01-01', updatedAt: '2024-01-01' },
];

const mockPositions: Position[] = [
  { id: '1', title: 'Desenvolvedor Full Stack', description: 'Desenvolvedor', level: 'PLENO', departmentId: '1', createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: '2', title: 'Analista de RH', description: 'Analista', level: 'JUNIOR', departmentId: '2', createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: '3', title: 'Gerente de Vendas', description: 'Gerente', level: 'SENIOR', departmentId: '3', createdAt: '2024-01-01', updatedAt: '2024-01-01' },
];

const mockSkills: Skill[] = [
  { id: '1', name: 'React', description: 'Biblioteca JavaScript', type: SkillType.HARD, category: SkillCategory.TECHNICAL, defaultLevel: SkillLevel.ADVANCED, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: '2', name: 'TypeScript', description: 'Superset do JavaScript', type: SkillType.HARD, category: SkillCategory.TECHNICAL, defaultLevel: SkillLevel.ADVANCED, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: '3', name: 'Comunicação', description: 'Habilidade de comunicação', type: SkillType.SOFT, category: SkillCategory.SOFT, defaultLevel: SkillLevel.INTERMEDIATE, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
];

const mockEmployees: Employee[] = [
  {
    id: '1',
    name: 'João Silva',
    email: 'joao.silva@example.com',
    phone: '(11) 99999-9999',
    hireDate: '2023-01-15',
    departmentId: '1',
    positionId: '1',
    status: 'ACTIVE',
    department: mockDepartments[0],
    position: mockPositions[0],
    managerId: 'manager-6', // Reporta para CTO
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '2',
    name: 'Maria Santos',
    email: 'maria.santos@example.com',
    phone: '(11) 88888-8888',
    hireDate: '2023-03-20',
    departmentId: '2',
    positionId: '2',
    status: 'ACTIVE',
    department: mockDepartments[1],
    position: mockPositions[1],
    managerId: 'manager-7', // Reporta para Head de RH
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '3',
    name: 'Pedro Oliveira',
    email: 'pedro.oliveira@example.com',
    phone: '(11) 77777-7777',
    hireDate: '2023-05-10',
    departmentId: '3',
    positionId: '3',
    status: 'ACTIVE',
    department: mockDepartments[2],
    position: mockPositions[2],
    managerId: 'manager-8', // Reporta para Diretor de Vendas
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '4',
    name: 'Ana Costa',
    email: 'ana.costa@example.com',
    phone: '(11) 66666-6666',
    hireDate: '2023-07-01',
    departmentId: '1',
    positionId: '1',
    status: 'ACTIVE',
    department: mockDepartments[0],
    position: mockPositions[0],
    managerId: 'manager-6', // Reporta para CTO
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '5',
    name: 'Carlos Pereira',
    email: 'carlos.pereira@example.com',
    phone: '(11) 55555-5555',
    hireDate: '2023-09-15',
    departmentId: '1',
    positionId: '1',
    status: 'ACTIVE',
    managerId: 'manager-6', // Reporta para CTO
    department: mockDepartments[0],
    position: mockPositions[0],
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '6',
    name: 'Fernanda Lima',
    email: 'fernanda.lima@example.com',
    phone: '(11) 44444-4444',
    hireDate: '2023-11-20',
    departmentId: '2',
    positionId: '2',
    status: 'ACTIVE',
    department: mockDepartments[1],
    position: mockPositions[1],
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '7',
    name: 'Roberto Almeida',
    email: 'roberto.almeida@example.com',
    phone: '(11) 33333-3333',
    hireDate: '2024-01-10',
    departmentId: '4',
    positionId: '1',
    status: 'ACTIVE',
    department: mockDepartments[3],
    position: mockPositions[0],
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '8',
    name: 'Juliana Ferreira',
    email: 'juliana.ferreira@example.com',
    phone: '(11) 22222-2222',
    hireDate: '2024-02-05',
    departmentId: '4',
    positionId: '3',
    status: 'ACTIVE',
    department: mockDepartments[3],
    position: mockPositions[2],
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  // Gestores (sem managerId)
  {
    id: 'manager-6',
    name: 'Carlos Mendes',
    email: 'carlos.mendes@example.com',
    phone: '(11) 66666-6666',
    hireDate: '2020-01-01',
    departmentId: '1',
    positionId: '6',
    status: 'ACTIVE',
    department: mockDepartments[0],
    position: { id: '6', title: 'CTO', description: 'Chief Technology Officer', level: 'SENIOR', departmentId: '1', createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 'manager-7',
    name: 'Ana Costa',
    email: 'ana.costa@example.com',
    phone: '(11) 55555-5555',
    hireDate: '2021-01-01',
    departmentId: '2',
    positionId: '7',
    status: 'ACTIVE',
    department: mockDepartments[1],
    position: { id: '7', title: 'Head de RH', description: 'Head of Human Resources', level: 'SENIOR', departmentId: '2', createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 'manager-8',
    name: 'Roberto Lima',
    email: 'roberto.lima@example.com',
    phone: '(11) 44444-4444',
    hireDate: '2022-01-01',
    departmentId: '3',
    positionId: '8',
    status: 'ACTIVE',
    department: mockDepartments[2],
    position: { id: '8', title: 'Diretor de Vendas', description: 'Sales Director', level: 'SENIOR', departmentId: '3', createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
];

const mockProjects: Project[] = [
  {
    id: '1',
    name: 'Sistema de Gestão',
    description: 'Sistema completo de gestão',
    startDate: '2024-01-01',
    endDate: '2024-06-30',
    status: ProjectStatus.IN_PROGRESS,
    budget: 50000,
    ownerId: '1',
    owner: mockEmployees[0],
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '2',
    name: 'Portal do Cliente',
    description: 'Portal para clientes',
    startDate: '2024-02-01',
    status: ProjectStatus.PLANNING,
    budget: 30000,
    ownerId: '2',
    owner: mockEmployees[1],
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
];

const mockTrainings: Training[] = [
  {
    id: '1',
    name: 'React Avançado',
    description: 'Curso de React avançado',
    provider: 'Udemy',
    type: 'ONLINE_COURSE',
    status: TrainingStatus.IN_PROGRESS,
    startDate: '2024-01-15',
    endDate: '2024-03-15',
    difficulty: 'ADVANCED',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '2',
    name: 'TypeScript Fundamentals',
    description: 'Curso completo de TypeScript',
    provider: 'Pluralsight',
    type: 'ONLINE_COURSE',
    status: TrainingStatus.COMPLETED,
    startDate: '2023-11-01',
    endDate: '2023-12-15',
    difficulty: 'INTERMEDIATE',
    createdAt: '2023-11-01',
    updatedAt: '2023-12-15',
  },
  {
    id: '3',
    name: 'Segurança da Informação',
    description: 'Treinamento obrigatório de segurança',
    provider: 'Empresa',
    type: 'INTERNAL_TRAINING',
    status: TrainingStatus.IN_PROGRESS,
    startDate: '2024-02-01',
    endDate: '2024-02-28',
    difficulty: 'BASIC',
    createdAt: '2024-02-01',
    updatedAt: '2024-02-01',
  },
  {
    id: '4',
    name: 'Workshop de Testes Automatizados',
    description: 'Workshop sobre Jest e React Testing Library',
    provider: 'Tech Conference',
    type: 'WORKSHOP',
    status: TrainingStatus.ENROLLED,
    startDate: '2024-04-10',
    endDate: '2024-04-12',
    difficulty: 'INTERMEDIATE',
    createdAt: '2024-02-15',
    updatedAt: '2024-02-15',
  },
  {
    id: '5',
    name: 'LGPD - Lei Geral de Proteção de Dados',
    description: 'Treinamento obrigatório sobre LGPD',
    provider: 'Empresa',
    type: 'INTERNAL_TRAINING',
    status: TrainingStatus.ENROLLED,
    startDate: '2024-03-01',
    endDate: '2024-03-31',
    difficulty: 'BASIC',
    createdAt: '2024-03-01',
    updatedAt: '2024-03-01',
  },
];

const mockGoals: Goal[] = [
  {
    id: '1',
    employeeId: '1',
    title: 'Completar projeto X',
    description: 'Finalizar projeto até junho',
    type: 'PROJECT',
    priority: 'HIGH',
    status: GoalStatus.IN_PROGRESS,
    startDate: '2024-01-01',
    targetDate: '2024-06-30',
    progress: 0.45, // 45% - progress is 0-1 (decimal)
    employee: mockEmployees[0],
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '2',
    employeeId: '1',
    title: 'Curso de React Avançado',
    description: 'Completar curso de React avançado na plataforma Udemy',
    type: 'DEVELOPMENT',
    priority: 'MEDIUM',
    status: GoalStatus.IN_PROGRESS,
    startDate: '2024-01-15',
    targetDate: '2024-03-15',
    progress: 0.75, // 75%
    employee: mockEmployees[0],
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '3',
    employeeId: '1',
    title: 'Treinamento de Segurança da Informação',
    description: 'Completar treinamento obrigatório de segurança da informação',
    type: 'DEVELOPMENT',
    priority: 'HIGH',
    status: GoalStatus.IN_PROGRESS,
    startDate: '2024-02-01',
    targetDate: '2024-02-28',
    progress: 0.30, // 30%
    employee: mockEmployees[0],
    createdAt: '2024-02-01',
    updatedAt: '2024-02-01',
  },
  {
    id: '4',
    employeeId: '1',
    title: 'Melhorar habilidades de comunicação',
    description: 'Participar de workshop de comunicação e apresentações',
    type: 'DEVELOPMENT',
    priority: 'MEDIUM',
    status: GoalStatus.IN_PROGRESS,
    startDate: '2024-01-20',
    targetDate: '2024-04-20',
    progress: 0.20, // 20%
    employee: mockEmployees[0],
    createdAt: '2024-01-20',
    updatedAt: '2024-01-20',
  },
  {
    id: '5',
    employeeId: '1',
    title: 'Certificação em TypeScript',
    description: 'Obter certificação oficial em TypeScript',
    type: 'CAREER',
    priority: 'HIGH',
    status: GoalStatus.IN_PROGRESS,
    startDate: '2024-02-10',
    targetDate: '2024-05-10',
    progress: 0.15, // 15%
    employee: mockEmployees[0],
    createdAt: '2024-02-10',
    updatedAt: '2024-02-10',
  },
  {
    id: '6',
    employeeId: '1',
    title: 'Treinamento de LGPD',
    description: 'Completar treinamento obrigatório sobre Lei Geral de Proteção de Dados',
    type: 'DEVELOPMENT',
    priority: 'HIGH',
    status: GoalStatus.PENDING,
    startDate: '2024-03-01',
    targetDate: '2024-03-31',
    progress: 0.0, // 0%
    employee: mockEmployees[0],
    createdAt: '2024-03-01',
    updatedAt: '2024-03-01',
  },
  {
    id: '7',
    employeeId: '1',
    title: 'Desenvolver habilidades de liderança',
    description: 'Participar de programa de desenvolvimento de liderança',
    type: 'CAREER',
    priority: 'MEDIUM',
    status: GoalStatus.IN_PROGRESS,
    startDate: '2024-01-10',
    targetDate: '2024-06-10',
    progress: 0.40, // 40%
    employee: mockEmployees[0],
    createdAt: '2024-01-10',
    updatedAt: '2024-01-10',
  },
  {
    id: '8',
    employeeId: '1',
    title: 'Curso de Testes Automatizados',
    description: 'Aprender Jest e React Testing Library',
    type: 'DEVELOPMENT',
    priority: 'MEDIUM',
    status: GoalStatus.IN_PROGRESS,
    startDate: '2024-02-15',
    targetDate: '2024-04-15',
    progress: 0.60, // 60%
    employee: mockEmployees[0],
    createdAt: '2024-02-15',
    updatedAt: '2024-02-15',
  },
];

const mockLeaveTypes: LeaveType[] = [
  {
    id: '1',
    name: 'Férias',
    code: 'VACATION',
    maxDays: 30,
    carryForward: true,
    requiresApproval: true,
    isActive: true,
  },
  {
    id: '2',
    name: 'Licença Médica',
    code: 'SICK_LEAVE',
    carryForward: false,
    requiresApproval: true,
    isActive: true,
  },
];

const mockLeaveRequests: LeaveRequest[] = [
  {
    id: '1',
    employeeId: '1',
    leaveTypeId: '1',
    startDate: '2024-02-15',
    endDate: '2024-02-20',
    days: 5,
    reason: 'Férias planejadas',
    status: LeaveRequestStatus.PENDING,
    leaveType: mockLeaveTypes[0],
    employee: mockEmployees[0],
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '2',
    employeeId: '2',
    leaveTypeId: '1',
    startDate: '2024-01-10',
    endDate: '2024-01-15',
    days: 5,
    reason: 'Férias de fim de ano',
    status: LeaveRequestStatus.APPROVED,
    leaveType: mockLeaveTypes[0],
    employee: mockEmployees[1],
    createdAt: '2023-12-20',
    updatedAt: '2023-12-22',
  },
  {
    id: '3',
    employeeId: '3',
    leaveTypeId: '2',
    startDate: '2024-03-01',
    endDate: '2024-03-01',
    days: 1,
    reason: 'Consulta médica',
    status: LeaveRequestStatus.PENDING,
    leaveType: mockLeaveTypes[1],
    employee: mockEmployees[2],
    createdAt: '2024-02-25',
    updatedAt: '2024-02-25',
  },
  {
    id: '4',
    employeeId: '4',
    leaveTypeId: '1',
    startDate: '2024-04-01',
    endDate: '2024-04-10',
    days: 8,
    reason: 'Viagem pessoal',
    status: LeaveRequestStatus.PENDING,
    leaveType: mockLeaveTypes[0],
    employee: mockEmployees[3],
    createdAt: '2024-03-01',
    updatedAt: '2024-03-01',
  },
];

const mockLeaveBalances: LeaveBalance[] = [
  {
    id: '1',
    employeeId: '1',
    leaveTypeId: '1',
    balance: 25,
    accrued: 30,
    used: 5,
    year: 2024,
    leaveType: mockLeaveTypes[0],
  },
];

const mockAttendance: Attendance[] = [
  {
    id: '1',
    employeeId: '1',
    date: new Date().toISOString().split('T')[0],
    checkIn: '09:00:00',
    checkOut: '18:00:00',
    workHours: 8,
    status: AttendanceStatus.PRESENT,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    employeeId: '1',
    date: new Date(Date.now() - 86400000).toISOString().split('T')[0], // Yesterday
    checkIn: '09:15:00',
    checkOut: '18:30:00',
    workHours: 8.25,
    status: AttendanceStatus.LATE,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: '3',
    employeeId: '1',
    date: new Date(Date.now() - 172800000).toISOString().split('T')[0], // 2 days ago
    checkIn: '08:45:00',
    checkOut: '17:45:00',
    workHours: 8,
    status: AttendanceStatus.PRESENT,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date(Date.now() - 172800000).toISOString(),
  },
];

const mockAttendanceSummary: AttendanceSummary = {
  totalDays: 30,
  present: 22,
  absent: 2,
  late: 3,
  onLeave: 3,
  totalWorkHours: 176,
  totalOvertimeHours: 8,
  averageWorkHours: 8,
};

const mockNotifications: Notification[] = [
  {
    id: '1',
    userId: '1',
    title: 'Nova avaliação disponível',
    message: 'Você tem uma nova avaliação de performance para preencher',
    channel: 'IN_APP',
    status: 'UNREAD',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

const mockAnalyticsOverview: AnalyticsOverview = {
  totalEmployees: mockEmployees.length,
  totalDepartments: mockDepartments.length,
  totalProjects: mockProjects.length,
  activeProjects: mockProjects.filter((p) => p.status === ProjectStatus.IN_PROGRESS).length,
  averagePerformance: 4.2,
  recentHires: 3,
};

const mockPerformanceTrends: PerformanceTrend[] = [
  { period: '2024-01', averageRating: 4.0, totalReviews: 10 },
  { period: '2024-02', averageRating: 4.2, totalReviews: 12 },
  { period: '2024-03', averageRating: 4.3, totalReviews: 15 },
];

const mockEmployeeProfile: EmployeeProfile = {
  id: '1',
  name: 'João Silva',
  email: 'joao.silva@company.com',
  phone: '+55 11 99999-9999',
  address: 'Rua das Flores, 123, São Paulo, SP',
  department: 'TI',
  position: 'Desenvolvedor Senior',
  hireDate: '2022-01-15',
  manager: 'Maria Santos',
  emergencyContact: {
    name: 'Ana Silva',
    relationship: 'Esposa',
    phone: '+55 11 88888-8888'
  }
};

const mockPolicies: PolicyDocument[] = [
  {
    id: '1',
    title: 'Código de Ética e Conduta',
    description: 'Diretrizes éticas para todos os funcionários',
    content: 'Conteúdo completo da política de ética...',
    category: PolicyCategory.ETHICS,
    status: PolicyStatus.ACTIVE,
    version: '2.1',
    effectiveDate: '2024-01-01',
    requiresAcknowledgment: true,
    createdBy: '1',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01'
  },
  {
    id: '2',
    title: 'Política de Segurança da Informação',
    description: 'Proteção de dados e informações confidenciais',
    content: 'Conteúdo completo da política de segurança...',
    category: PolicyCategory.SECURITY,
    status: PolicyStatus.ACTIVE,
    version: '1.5',
    effectiveDate: '2024-02-01',
    requiresAcknowledgment: true,
    createdBy: '1',
    createdAt: '2024-02-01',
    updatedAt: '2024-02-01'
  },
  {
    id: '3',
    title: 'Política de Licenças e Férias',
    description: 'Regras para concessão de licenças e férias',
    content: 'Conteúdo completo da política de licenças...',
    category: PolicyCategory.HR,
    status: PolicyStatus.ACTIVE,
    version: '3.0',
    effectiveDate: '2024-01-15',
    requiresAcknowledgment: false,
    createdBy: '1',
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15'
  },
  {
    id: '4',
    title: 'Política de Uso de Recursos Tecnológicos',
    description: 'Regras para uso de equipamentos e internet',
    content: 'Conteúdo completo da política de TI...',
    category: PolicyCategory.IT,
    status: PolicyStatus.PENDING_APPROVAL,
    version: '1.0',
    effectiveDate: '2024-04-01',
    requiresAcknowledgment: true,
    createdBy: '1',
    createdAt: '2024-03-01',
    updatedAt: '2024-03-01'
  }
];

const mockPolicyAcknowledgments: PolicyAcknowledgment[] = [
  {
    id: '1',
    policyId: '1',
    policyTitle: 'Código de Ética e Conduta',
    employeeId: '1',
    employeeName: 'João Silva',
    acknowledgedAt: '2024-01-15T10:30:00Z',
    versionAcknowledged: '2.1'
  },
  {
    id: '2',
    policyId: '3',
    policyTitle: 'Política de Licenças e Férias',
    employeeId: '1',
    employeeName: 'João Silva',
    acknowledgedAt: '2024-02-01T14:20:00Z',
    versionAcknowledged: '3.0'
  }
];

const mockPerformanceReviews: PerformanceReview[] = [
  {
    id: '1',
    employeeId: '1',
    reviewerId: '2',
    periodStart: '2024-01-01',
    periodEnd: '2024-03-31',
    status: PerformanceReviewStatus.COMPLETED,
    overallRating: 4.5,
    strengths: ['Bom trabalho em equipe', 'Proativo'],
    improvements: ['Melhorar comunicação'],
    employee: mockEmployees[0],
    reviewer: mockEmployees[1],
    createdAt: '2024-04-01',
    updatedAt: '2024-04-01',
  },
];

const mockFeedback: Feedback[] = [
  {
    id: '1',
    authorId: '2',
    recipientId: '1',
    type: 'PERFORMANCE',
    sentiment: 'POSITIVE',
    title: 'Excelente trabalho',
    content: 'Parabéns pelo trabalho realizado no projeto X',
    rating: 5,
    author: mockEmployees[1],
    recipient: mockEmployees[0],
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
];

const mockAchievements: Achievement[] = [
  {
    id: '1',
    employeeId: '1',
    title: 'Certificação TypeScript',
    description: 'Certificação oficial em TypeScript pela Microsoft',
    type: AchievementType.CERTIFICATION,
    icon: '🏆',
    earnedAt: '2023-12-15',
    issuer: 'Microsoft',
    certificateUrl: 'https://example.com/certificate-ts',
    employee: mockEmployees[0],
    createdAt: '2023-12-15',
    updatedAt: '2023-12-15',
  },
  {
    id: '2',
    employeeId: '1',
    title: 'Badge de React Expert',
    description: 'Conquistado por completar 10 projetos em React',
    type: AchievementType.BADGE,
    icon: '🎖️',
    earnedAt: '2024-01-20',
    issuer: 'Empresa',
    employee: mockEmployees[0],
    createdAt: '2024-01-20',
    updatedAt: '2024-01-20',
  },
  {
    id: '3',
    employeeId: '1',
    title: 'Milestone: 1 Ano na Empresa',
    description: 'Completou 1 ano de dedicação e excelência',
    type: AchievementType.MILESTONE,
    icon: '⭐',
    earnedAt: '2024-01-15',
    issuer: 'Empresa',
    employee: mockEmployees[0],
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '4',
    employeeId: '1',
    title: 'Funcionário do Mês',
    description: 'Reconhecido por excelente desempenho em janeiro',
    type: AchievementType.AWARD,
    icon: '🏅',
    earnedAt: '2024-02-01',
    issuer: 'RH',
    employee: mockEmployees[0],
    createdAt: '2024-02-01',
    updatedAt: '2024-02-01',
  },
  {
    id: '5',
    employeeId: '1',
    title: 'Master em JavaScript',
    description: 'Dominou todas as habilidades avançadas de JavaScript',
    type: AchievementType.SKILL_MASTERY,
    icon: '💎',
    earnedAt: '2023-11-30',
    issuer: 'Plataforma de Treinamento',
    employee: mockEmployees[0],
    createdAt: '2023-11-30',
    updatedAt: '2023-11-30',
  },
];

export const mockPayrolls: Payroll[] = [
  {
    id: '1',
    employeeId: '1',
    period: '2025-02',
    baseSalary: 12000,
    grossSalary: 12500,
    totalDeductions: 2500,
    netSalary: 10000,
    status: PayrollStatus.PAID,
    paidAt: '2025-02-28T10:00:00Z',
    items: [
      { id: '1', name: 'Salário Base', type: 'EARNING', amount: 12000, taxable: true },
      { id: '2', name: 'Hora Extra', type: 'EARNING', amount: 500, taxable: true },
      { id: '3', name: 'INSS', type: 'DEDUCTION', amount: 1000, taxable: false },
      { id: '4', name: 'IRRF', type: 'DEDUCTION', amount: 1500, taxable: false },
    ],
    createdAt: '2025-02-25',
    updatedAt: '2025-02-28'
  },
  {
    id: '2',
    employeeId: '1',
    period: '2025-01',
    baseSalary: 12000,
    grossSalary: 12000,
    totalDeductions: 2400,
    netSalary: 9600,
    status: PayrollStatus.PAID,
    paidAt: '2025-01-30T10:00:00Z',
    items: [
      { id: '1', name: 'Salário Base', type: 'EARNING', amount: 12000, taxable: true },
      { id: '2', name: 'INSS', type: 'DEDUCTION', amount: 1000, taxable: false },
      { id: '3', name: 'IRRF', type: 'DEDUCTION', amount: 1400, taxable: false },
    ],
    createdAt: '2025-01-25',
    updatedAt: '2025-01-30'
  },
  // Adiantamento 13º
  {
    id: '3',
    employeeId: '1',
    period: '2024-11',
    baseSalary: 12000,
    grossSalary: 6000,
    totalDeductions: 0,
    netSalary: 6000,
    status: PayrollStatus.PAID,
    paidAt: '2024-11-30T10:00:00Z',
    items: [
      { id: '1', name: '1ª Parcela 13º Salário', type: 'EARNING', amount: 6000, taxable: true }
    ],
    createdAt: '2024-11-25',
    updatedAt: '2024-11-30'
  },
  // PLR
  {
    id: '4',
    employeeId: '1',
    period: '2025-03',
    baseSalary: 12000,
    grossSalary: 25000,
    totalDeductions: 5000,
    netSalary: 20000,
    status: PayrollStatus.PROCESSED,
    paidAt: '2025-03-15T10:00:00Z',
    items: [
      { id: '1', name: 'PLR 2024', type: 'EARNING', amount: 25000, taxable: true },
      { id: '2', name: 'IRRF S/ PLR', type: 'DEDUCTION', amount: 5000, taxable: false }
    ],
    createdAt: '2025-03-10',
    updatedAt: '2025-03-10'
  }
];

const mockDashboardData: DashboardData = {
  profile: mockEmployees[0],
  leaveBalances: mockLeaveBalances,
  recentAttendance: mockAttendance,
  goals: mockGoals,
  trainings: mockTrainings,
  performanceReviews: mockPerformanceReviews,
  achievements: mockAchievements,
};

// Mock Benefits
const mockBenefits: any[] = [
  {
    id: '1',
    name: 'Plano de Saúde Premium',
    description: 'Cobertura nacional com rede credenciada ampla',
    category: 'HEALTH',
    type: 'INSURANCE',
    cost: 800,
    employeeCost: 150,
    coverage: 'Nacional - Coparticipação 20%',
    eligibility: ['EMPLOYEE'],
    allowsDependents: true,
    status: 'ACTIVE',
  },
  {
    id: '2',
    name: 'Plano Odontológico',
    description: 'Cobertura para procedimentos odontológicos',
    category: 'DENTAL',
    type: 'INSURANCE',
    cost: 120,
    employeeCost: 30,
    coverage: 'Nacional',
    eligibility: ['EMPLOYEE'],
    allowsDependents: true,
    status: 'ACTIVE',
  },
  {
    id: '3',
    name: 'Vale Refeição',
    description: 'R$ 35,00 por dia útil',
    category: 'MEAL',
    type: 'VOUCHER',
    cost: 770,
    employeeCost: 0,
    coverage: 'Aceito em estabelecimentos credenciados',
    eligibility: ['EMPLOYEE'],
    allowsDependents: false,
    status: 'ACTIVE',
  },
  {
    id: '4',
    name: 'Vale Transporte',
    description: 'Custeio de transporte público',
    category: 'TRANSPORT',
    type: 'VOUCHER',
    cost: 250,
    employeeCost: 0,
    coverage: 'Transporte público municipal',
    eligibility: ['EMPLOYEE'],
    allowsDependents: false,
    status: 'ACTIVE',
  },
  {
    id: '5',
    name: 'Seguro de Vida',
    description: 'Cobertura de R$ 200.000',
    category: 'LIFE_INSURANCE',
    type: 'INSURANCE',
    cost: 50,
    employeeCost: 0,
    coverage: 'Cobertura nacional',
    eligibility: ['EMPLOYEE'],
    allowsDependents: false,
    status: 'ACTIVE',
  },
  {
    id: '6',
    name: 'Gympass',
    description: 'Acesso a academias e studios',
    category: 'WELLNESS',
    type: 'SUBSCRIPTION',
    cost: 80,
    employeeCost: 20,
    coverage: 'Rede credenciada Gympass',
    eligibility: ['EMPLOYEE'],
    allowsDependents: false,
    status: 'ACTIVE',
  },
];

const mockEnrollments: any[] = [
  {
    id: '1',
    employeeId: '1',
    benefitId: '1',
    benefit: mockBenefits[0],
    status: 'ACTIVE',
    enrolledAt: '2024-01-15',
    effectiveDate: '2024-02-01',
    dependents: [
      {
        id: 'd1',
        name: 'Maria Silva',
        relationship: 'SPOUSE',
        birthDate: '1992-05-10',
        cpf: '123.456.789-00',
      },
      {
        id: 'd2',
        name: 'Pedro Silva',
        relationship: 'CHILD',
        birthDate: '2015-08-20',
        cpf: '987.654.321-00',
      },
    ],
  },
  {
    id: '2',
    employeeId: '1',
    benefitId: '3',
    benefit: mockBenefits[2],
    status: 'ACTIVE',
    enrolledAt: '2024-01-15',
    effectiveDate: '2024-02-01',
  },
  {
    id: '3',
    employeeId: '1',
    benefitId: '5',
    benefit: mockBenefits[4],
    status: 'ACTIVE',
    enrolledAt: '2024-01-15',
    effectiveDate: '2024-02-01',
  },
];

export const mockSeparations: Separation[] = [
  {
    id: '1',
    employeeId: '3',
    type: SeparationType.RESIGNATION,
    status: SeparationStatus.IN_PROGRESS,
    lastWorkingDate: '2024-12-31',
    noticePeriodDays: 30,
    reason: 'Aceitou proposta de outra empresa',
    exitInterviewCompleted: false,
    exitInterviewDate: '2024-12-20',
    finalPaymentCalculated: false,
    checklistItems: [
      { id: '1', title: 'Devolução de equipamentos', completed: false, completedBy: '', completedAt: '' },
      { id: '2', title: 'Desligamento de acessos', completed: false, completedBy: '', completedAt: '' },
      { id: '3', title: 'Entrevista de desligamento', completed: false, completedBy: '', completedAt: '' },
    ],
    createdAt: '2024-11-15',
    updatedAt: '2024-11-15',
  },
  {
    id: '2',
    employeeId: '5',
    type: SeparationType.RETIREMENT,
    status: SeparationStatus.COMPLETED,
    lastWorkingDate: '2024-10-31',
    noticePeriodDays: 60,
    reason: 'Aposentadoria por tempo de contribuição',
    exitInterviewCompleted: true,
    exitInterviewDate: '2024-10-25',
    exitInterviewNotes: 'Funcionário expressou gratidão pela empresa e pelos anos de trabalho.',
    finalPaymentCalculated: true,
    checklistItems: [
      { id: '1', title: 'Devolução de equipamentos', completed: true, completedBy: 'Admin', completedAt: '2024-10-30' },
      { id: '2', title: 'Desligamento de acessos', completed: true, completedBy: 'TI', completedAt: '2024-10-31' },
      { id: '3', title: 'Entrevista de desligamento', completed: true, completedBy: 'RH', completedAt: '2024-10-25' },
    ],
    createdAt: '2024-09-01',
    updatedAt: '2024-10-31',
  },
  {
    id: '3',
    employeeId: '7',
    type: SeparationType.TERMINATION,
    status: SeparationStatus.PENDING_APPROVAL,
    lastWorkingDate: '2024-12-15',
    noticePeriodDays: 0,
    reason: 'Justa causa - violação de política da empresa',
    exitInterviewCompleted: false,
    finalPaymentCalculated: false,
    checklistItems: [],
    createdAt: '2024-12-01',
    updatedAt: '2024-12-01',
  },
];

// Mock Payroll Management
const mockPayrollCycles: any[] = [
  {
    id: '1',
    referenceMonth: '2025-11',
    status: 'PAID',
    totalEmployees: 11,
    totalGross: 165000,
    totalDeductions: 35000,
    totalNet: 130000,
    calculatedAt: '2025-11-25T10:00:00Z',
    approvedAt: '2025-11-26T14:00:00Z',
    approvedBy: '1',
    processedAt: '2025-11-28T09:00:00Z',
    paidAt: '2025-11-30T10:00:00Z',
    paymentDate: '2025-11-30',
    createdAt: '2025-11-20',
    updatedAt: '2025-11-30',
  },
  {
    id: '2',
    referenceMonth: '2025-10',
    status: 'CLOSED',
    totalEmployees: 11,
    totalGross: 162000,
    totalDeductions: 34500,
    totalNet: 127500,
    calculatedAt: '2025-10-25T10:00:00Z',
    approvedAt: '2025-10-26T14:00:00Z',
    approvedBy: '1',
    processedAt: '2025-10-28T09:00:00Z',
    paidAt: '2025-10-30T10:00:00Z',
    paymentDate: '2025-10-30',
    createdAt: '2025-10-20',
    updatedAt: '2025-10-31',
  },
  {
    id: '3',
    referenceMonth: '2025-12',
    status: 'PENDING_APPROVAL',
    totalEmployees: 11,
    totalGross: 168000,
    totalDeductions: 36000,
    totalNet: 132000,
    calculatedAt: '2025-12-20T10:00:00Z',
    paymentDate: '2025-12-30',
    createdAt: '2025-12-15',
    updatedAt: '2025-12-20',
    notes: 'Inclui 13º salário (2ª parcela)',
  },
];

const mockDepartmentPayrollSummaries: any[] = [
  {
    id: '1',
    payrollCycleId: '3',
    departmentId: '1',
    departmentName: 'Tecnologia',
    employeeCount: 4,
    totalGross: 62000,
    totalDeductions: 13200,
    totalNet: 48800,
    status: 'CALCULATED',
  },
  {
    id: '2',
    payrollCycleId: '3',
    departmentId: '2',
    departmentName: 'Recursos Humanos',
    employeeCount: 3,
    totalGross: 38000,
    totalDeductions: 8100,
    totalNet: 29900,
    status: 'CALCULATED',
  },
  {
    id: '3',
    payrollCycleId: '3',
    departmentId: '3',
    departmentName: 'Vendas',
    employeeCount: 2,
    totalGross: 32000,
    totalDeductions: 6800,
    totalNet: 25200,
    status: 'CALCULATED',
  },
  {
    id: '4',
    payrollCycleId: '3',
    departmentId: '4',
    departmentName: 'Financeiro',
    employeeCount: 2,
    totalGross: 36000,
    totalDeductions: 7900,
    totalNet: 28100,
    status: 'CALCULATED',
  },
];

const mockPayrollApprovals: any[] = [
  {
    id: '1',
    payrollCycleId: '3',
    approverId: '1',
    status: 'PENDING',
    createdAt: '2025-12-20T10:00:00Z',
  },
];

const mockPayrollNotifications: any[] = [
  {
    id: '1',
    payrollCycleId: '3',
    recipientType: 'FINANCE',
    subject: 'Folha de Pagamento Dez/2025 - Aguardando Aprovação',
    message: 'A folha de pagamento do mês de dezembro/2025 foi calculada e está aguardando aprovação.',
    createdAt: '2025-12-20T10:05:00Z',
  },
];

const mockPayrollReports: any[] = [
  {
    id: '1',
    payrollCycleId: '1',
    reportType: 'SUMMARY',
    format: 'PDF',
    generatedAt: '2025-11-30T15:00:00Z',
    generatedBy: '1',
  },
  {
    id: '2',
    payrollCycleId: '1',
    reportType: 'BY_DEPARTMENT',
    format: 'EXCEL',
    generatedAt: '2025-11-30T16:00:00Z',
    generatedBy: '1',
  },
];

// Mock Employee Payroll Details - Baseado nos payrolls existentes
const mockEmployeePayrollDetails: any[] = mockPayrolls.map((payroll: any) => {
  const employee = mockEmployees.find((e: any) => e.id === payroll.employeeId);
  const earnings = payroll.items.filter((i: any) => i.type === 'EARNING');
  const deductions = payroll.items.filter((i: any) => i.type === 'DEDUCTION');
  
  return {
    employeeId: payroll.employeeId,
    employee: employee,
    departmentId: employee?.departmentId || '1',
    costCenterId: undefined,
    baseSalary: payroll.baseSalary,
    earnings: earnings,
    deductions: deductions,
    grossSalary: payroll.grossSalary,
    totalDeductions: payroll.totalDeductions,
    netSalary: payroll.netSalary,
    status: payroll.status === PayrollStatus.PAID ? 'PAID' : 'CALCULATED',
  };
});

export const mockData = {
  employees: mockEmployees,
  departments: mockDepartments,
  positions: mockPositions,
  skills: mockSkills,
  projects: mockProjects,
  trainings: mockTrainings,
  goals: mockGoals,
  leaveTypes: mockLeaveTypes,
  leaveRequests: mockLeaveRequests,
  leaveBalances: mockLeaveBalances,
  attendance: mockAttendance,
  attendanceSummary: mockAttendanceSummary,
  notifications: mockNotifications,
  analyticsOverview: mockAnalyticsOverview,
  employeeProfile: mockEmployeeProfile,
  policies: mockPolicies,
  policyAcknowledgments: mockPolicyAcknowledgments,
  performanceTrends: mockPerformanceTrends,
  dashboardData: mockDashboardData,
  performanceReviews: mockPerformanceReviews,
  feedback: mockFeedback,
  achievements: mockAchievements,
  generateId,
  payrolls: mockPayrolls,
  benefits: mockBenefits,
  enrollments: mockEnrollments,
  separations: mockSeparations,
  payrollCycles: mockPayrollCycles,
  departmentPayrollSummaries: mockDepartmentPayrollSummaries,
  payrollApprovals: mockPayrollApprovals,
  payrollNotifications: mockPayrollNotifications,
  employeePayrollDetails: mockEmployeePayrollDetails,
  payrollReports: mockPayrollReports,
};

const mockProjectAllocations: ProjectAllocation[] = [
  {
    id: '1',
    employeeId: '1',
    projectId: '1',
    role: 'Desenvolvedor Full Stack',
    allocationPercentage: 100,
    startDate: '2024-01-01',
    endDate: '2024-06-30',
    status: AllocationStatus.ACTIVE,
    notes: 'Alocado como desenvolvedor principal',
    employee: mockData.employees[0],
    project: mockData.projects[0],
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '2',
    employeeId: '2',
    projectId: '1',
    role: 'Analista de Requisitos',
    allocationPercentage: 50,
    startDate: '2024-01-15',
    status: AllocationStatus.ACTIVE,
    employee: mockData.employees[1],
    project: mockData.projects[0],
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '3',
    employeeId: '3',
    projectId: '2',
    role: 'Gerente de Projeto',
    allocationPercentage: 75,
    startDate: '2024-02-01',
    status: AllocationStatus.ACTIVE,
    employee: mockData.employees[2],
    project: mockData.projects[1],
    createdAt: '2024-02-01',
    updatedAt: '2024-02-01',
  },
];

export const mockAllocationData = {
  projectAllocations: mockProjectAllocations,
};

const mockMentoringRelationships: MentoringRelationship[] = [
  {
    id: '1',
    mentorId: '2',
    menteeId: '1',
    status: MentoringStatus.ACTIVE,
    startDate: '2024-01-15',
    mentor: mockEmployees[1],
    mentee: mockEmployees[0],
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '2',
    mentorId: '3',
    menteeId: '2',
    status: MentoringStatus.ACTIVE,
    startDate: '2024-02-01',
    mentor: mockEmployees[2],
    mentee: mockEmployees[1],
    createdAt: '2024-02-01',
    updatedAt: '2024-02-01',
  },
  {
    id: '3',
    mentorId: '2',
    menteeId: '3',
    status: MentoringStatus.COMPLETED,
    startDate: '2023-06-01',
    endDate: '2023-12-31',
    mentor: mockEmployees[1],
    mentee: mockEmployees[2],
    createdAt: '2023-06-01',
    updatedAt: '2023-12-31',
  },
];

export { mockMentoringRelationships };

const mockContractors: Contractor[] = [
  {
    id: '1',
    name: 'João Santos',
    companyName: 'TechServ Soluções Ltda',
    contactEmail: 'joao@techserv.com',
    contactPhone: '(11) 98765-4321',
    address: 'Rua das Flores, 123 - São Paulo, SP',
    taxId: '12.345.678/0001-90',
    isActive: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '2',
    name: 'Maria Silva',
    companyName: 'BuildPro Construtora',
    contactEmail: 'maria@buildpro.com',
    contactPhone: '(11) 97654-3210',
    address: 'Av. Paulista, 1000 - São Paulo, SP',
    taxId: '98.765.432/0001-10',
    isActive: true,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '3',
    name: 'Carlos Oliveira',
    companyName: 'FastWork Serviços',
    contactEmail: 'carlos@fastwork.com',
    contactPhone: '(11) 96543-2109',
    taxId: '11.222.333/0001-44',
    isActive: false,
    createdAt: '2023-06-01',
    updatedAt: '2024-02-01',
  },
];

const mockContractLabor: ContractLabor[] = [
  {
    id: '1',
    contractorId: '1',
    contractor: mockContractors[0],
    name: 'Pedro Almeida',
    skill: 'Desenvolvedor Frontend',
    wage: 8500,
    currency: 'BRL',
    status: ContractLaborStatus.ACTIVE,
    projectId: mockProjects[0]?.id,
    project: mockProjects[0],
    startDate: '2024-01-15',
    endDate: '2024-12-31',
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '2',
    contractorId: '1',
    contractor: mockContractors[0],
    name: 'Ana Costa',
    skill: 'Designer UX/UI',
    wage: 7000,
    currency: 'BRL',
    status: ContractLaborStatus.ACTIVE,
    projectId: mockProjects[0]?.id,
    project: mockProjects[0],
    startDate: '2024-02-01',
    createdAt: '2024-02-01',
    updatedAt: '2024-02-01',
  },
  {
    id: '3',
    contractorId: '2',
    contractor: mockContractors[1],
    name: 'Ricardo Mendes',
    skill: 'Engenheiro Civil',
    wage: 12000,
    currency: 'BRL',
    status: ContractLaborStatus.ACTIVE,
    startDate: '2024-01-10',
    endDate: '2024-06-30',
    createdAt: '2024-01-10',
    updatedAt: '2024-01-10',
  },
  {
    id: '4',
    contractorId: '2',
    contractor: mockContractors[1],
    name: 'Juliana Ferreira',
    skill: 'Arquiteta',
    wage: 10000,
    currency: 'BRL',
    status: ContractLaborStatus.INACTIVE,
    startDate: '2023-12-01',
    endDate: '2024-03-31',
    createdAt: '2023-12-01',
    updatedAt: '2024-03-31',
  },
  {
    id: '5',
    contractorId: '3',
    contractor: mockContractors[2],
    name: 'Fernando Lima',
    skill: 'Técnico de TI',
    wage: 5500,
    currency: 'BRL',
    status: ContractLaborStatus.TERMINATED,
    startDate: '2023-06-01',
    endDate: '2023-12-15',
    createdAt: '2023-06-01',
    updatedAt: '2023-12-15',
  },
];

const mockContractLaborAttendance: ContractLaborAttendance[] = [
  {
    id: '1',
    laborId: '1',
    date: '2024-11-01',
    hoursWorked: 8,
    notes: 'Trabalho normal',
  },
  {
    id: '2',
    laborId: '1',
    date: '2024-11-04',
    hoursWorked: 8,
    notes: 'Desenvolvimento de features',
  },
  {
    id: '3',
    laborId: '1',
    date: '2024-11-05',
    hoursWorked: 6,
    notes: 'Saída antecipada',
  },
  {
    id: '4',
    laborId: '2',
    date: '2024-11-01',
    hoursWorked: 8,
  },
  {
    id: '5',
    laborId: '2',
    date: '2024-11-04',
    hoursWorked: 8,
  },
  {
    id: '6',
    laborId: '3',
    date: '2024-11-01',
    hoursWorked: 10,
    notes: 'Hora extra',
  },
];

export { mockContractors, mockContractLabor, mockContractLaborAttendance };

const mockServiceRequests: ServiceRequest[] = [
  {
    id: '1',
    title: 'Desenvolvimento de Sistema de CRM',
    description: 'Precisamos de uma equipe para desenvolver um sistema CRM customizado para nossa empresa. O sistema deve incluir gestão de leads, funil de vendas, relatórios e integrações com WhatsApp e Email.',
    category: 'Desenvolvimento de Software',
    skills: ['React', 'Node.js', 'PostgreSQL', 'API REST'],
    budget: {
      min: 50000,
      max: 80000,
      currency: 'BRL',
    },
    priority: ServiceRequestPriority.HIGH,
    status: ServiceRequestStatus.OPEN,
    deadline: '2024-12-31',
    remote: true,
    projectId: mockProjects[0]?.id,
    project: mockProjects[0],
    createdBy: '1',
    createdByName: 'João Silva',
    proposalsCount: 3,
    createdAt: '2024-11-15',
    updatedAt: '2024-11-15',
  },
  {
    id: '2',
    title: 'Designer UX/UI para Aplicativo Mobile',
    description: 'Buscamos designer especializado em UX/UI para criar a interface de um aplicativo mobile de delivery. Precisa ter experiência com design system e prototipagem.',
    category: 'Design',
    skills: ['Figma', 'UI/UX', 'Design System', 'Prototipagem'],
    budget: {
      min: 15000,
      max: 25000,
      currency: 'BRL',
    },
    priority: ServiceRequestPriority.MEDIUM,
    status: ServiceRequestStatus.OPEN,
    deadline: '2024-11-30',
    remote: true,
    createdBy: '1',
    createdByName: 'João Silva',
    proposalsCount: 5,
    createdAt: '2024-11-10',
    updatedAt: '2024-11-18',
  },
  {
    id: '3',
    title: 'Consultoria em Infraestrutura Cloud AWS',
    description: 'Necessitamos de consultoria especializada em AWS para migrar nossa infraestrutura on-premise para a nuvem. Inclui arquitetura, implementação e treinamento da equipe.',
    category: 'Infraestrutura e DevOps',
    skills: ['AWS', 'Docker', 'Kubernetes', 'Terraform'],
    budget: {
      min: 30000,
      max: 50000,
      currency: 'BRL',
    },
    priority: ServiceRequestPriority.URGENT,
    status: ServiceRequestStatus.IN_REVIEW,
    deadline: '2024-12-15',
    location: 'São Paulo, SP',
    remote: false,
    createdBy: '2',
    createdByName: 'Maria Santos',
    proposalsCount: 2,
    createdAt: '2024-11-12',
    updatedAt: '2024-11-19',
  },
  {
    id: '4',
    title: 'Engenheiro Civil para Reforma de Escritório',
    description: 'Reforma completa do escritório de 500m². Precisa de engenheiro civil para projeto estrutural e acompanhamento da obra.',
    category: 'Engenharia Civil',
    skills: ['AutoCAD', 'Projetos Estruturais', 'Gerenciamento de Obras'],
    budget: {
      min: 20000,
      max: 35000,
      currency: 'BRL',
    },
    priority: ServiceRequestPriority.HIGH,
    status: ServiceRequestStatus.OPEN,
    deadline: '2025-01-31',
    location: 'São Paulo, SP - Av. Paulista',
    remote: false,
    createdBy: '1',
    createdByName: 'João Silva',
    proposalsCount: 4,
    createdAt: '2024-11-08',
    updatedAt: '2024-11-08',
  },
  {
    id: '5',
    title: 'Especialista em Marketing Digital',
    description: 'Procuramos especialista em marketing digital para campanha de lançamento de produto. Precisa ter experiência com Google Ads, Facebook Ads e estratégias de inbound marketing.',
    category: 'Marketing',
    skills: ['Google Ads', 'Facebook Ads', 'SEO', 'Inbound Marketing'],
    budget: {
      min: 10000,
      max: 18000,
      currency: 'BRL',
    },
    priority: ServiceRequestPriority.MEDIUM,
    status: ServiceRequestStatus.OPEN,
    deadline: '2024-12-01',
    remote: true,
    createdBy: '3',
    createdByName: 'Pedro Costa',
    proposalsCount: 6,
    createdAt: '2024-11-05',
    updatedAt: '2024-11-16',
  },
  {
    id: '6',
    title: 'Desenvolvedor Mobile React Native',
    description: 'Desenvolvimento de aplicativo mobile para iOS e Android usando React Native. App de gestão de tarefas com sincronização em tempo real.',
    category: 'Desenvolvimento Mobile',
    skills: ['React Native', 'TypeScript', 'Firebase', 'Redux'],
    budget: {
      min: 35000,
      max: 55000,
      currency: 'BRL',
    },
    priority: ServiceRequestPriority.LOW,
    status: ServiceRequestStatus.CLOSED,
    deadline: '2024-11-20',
    remote: true,
    createdBy: '1',
    createdByName: 'João Silva',
    proposalsCount: 8,
    createdAt: '2024-10-15',
    updatedAt: '2024-11-01',
    closedAt: '2024-11-01',
  },
];

const mockServiceProposals: ServiceProposal[] = [
  {
    id: '1',
    serviceRequestId: '1',
    contractorId: '1',
    contractor: mockContractors[0],
    title: 'Proposta Completa para Sistema CRM',
    description: 'Oferecemos desenvolvimento completo do sistema CRM com tecnologias modernas. Nossa equipe tem 5 anos de experiência em projetos similares. Incluímos 3 meses de suporte pós-entrega.',
    proposedBudget: 65000,
    currency: 'BRL',
    estimatedDuration: '4 meses',
    deliverables: [
      'Análise de requisitos completa',
      'Protótipos de telas',
      'Sistema completo com testes',
      'Documentação técnica',
      'Treinamento da equipe',
      '3 meses de suporte',
    ],
    status: ProposalStatus.SUBMITTED,
    submittedAt: '2024-11-16T10:30:00',
    createdAt: '2024-11-16T10:30:00',
    updatedAt: '2024-11-16T10:30:00',
  },
  {
    id: '2',
    serviceRequestId: '1',
    contractorId: '2',
    contractor: mockContractors[1],
    title: 'CRM Sob Medida com Integrações',
    description: 'Desenvolvimento de CRM com foco em integrações. Temos expertise em integração com WhatsApp Business API, SendGrid e outras plataformas.',
    proposedBudget: 72000,
    currency: 'BRL',
    estimatedDuration: '5 meses',
    deliverables: [
      'Sistema CRM completo',
      'Integrações com WhatsApp e Email',
      'Dashboard de analytics',
      'App mobile complementar',
      'Suporte por 6 meses',
    ],
    status: ProposalStatus.UNDER_REVIEW,
    submittedAt: '2024-11-17T14:20:00',
    reviewedAt: '2024-11-18T09:00:00',
    reviewedBy: '1',
    createdAt: '2024-11-17T14:20:00',
    updatedAt: '2024-11-18T09:00:00',
  },
  {
    id: '3',
    serviceRequestId: '2',
    contractorId: '1',
    contractor: mockContractors[0],
    title: 'Design System Completo para App',
    description: 'Criação de design system completo, protótipos interativos e guia de estilo. Experiência com apps de delivery e e-commerce.',
    proposedBudget: 18000,
    currency: 'BRL',
    estimatedDuration: '6 semanas',
    deliverables: [
      'Design system no Figma',
      'Protótipos de alta fidelidade',
      'Guia de estilo',
      'Biblioteca de componentes',
      '2 revisões incluídas',
    ],
    status: ProposalStatus.ACCEPTED,
    submittedAt: '2024-11-11T16:00:00',
    reviewedAt: '2024-11-13T10:30:00',
    reviewedBy: '1',
    reviewNotes: 'Proposta aprovada. Portfolio excelente e orçamento dentro do esperado.',
    createdAt: '2024-11-11T16:00:00',
    updatedAt: '2024-11-13T10:30:00',
  },
  {
    id: '4',
    serviceRequestId: '3',
    contractorId: '2',
    contractor: mockContractors[1],
    title: 'Migração e Otimização AWS',
    description: 'Migração completa para AWS com arquitetura otimizada. Incluímos análise de custos, implementação de CI/CD e treinamento hands-on.',
    proposedBudget: 42000,
    currency: 'BRL',
    estimatedDuration: '3 meses',
    deliverables: [
      'Arquitetura cloud documentada',
      'Migração de serviços',
      'Pipeline CI/CD',
      'Monitoramento e alertas',
      'Treinamento da equipe (40h)',
      'Suporte por 3 meses',
    ],
    status: ProposalStatus.SUBMITTED,
    submittedAt: '2024-11-14T11:00:00',
    createdAt: '2024-11-14T11:00:00',
    updatedAt: '2024-11-14T11:00:00',
  },
];

const mockServiceBookings: ServiceBooking[] = [
  {
    id: '1',
    serviceRequestId: '2',
    proposalId: '3',
    contractorId: '1',
    contractor: mockContractors[0],
    title: 'Briefing - Design App de Delivery',
    description: 'Reunião inicial para alinhamento de expectativas, apresentação do portfolio e discussão dos requisitos do projeto.',
    scheduledDate: '2024-11-25',
    startTime: '14:00',
    endTime: '15:30',
    duration: 90,
    meetingLink: 'https://meet.google.com/abc-defg-hij',
    status: BookingStatus.CONFIRMED,
    attendees: ['João Silva', 'Maria Santos', 'Designer da TechServ'],
    notes: 'Trazer exemplos de apps similares e lista de funcionalidades prioritárias.',
    createdBy: '1',
    createdAt: '2024-11-13T15:00:00',
    updatedAt: '2024-11-14T09:00:00',
  },
  {
    id: '2',
    serviceRequestId: '1',
    contractorId: '1',
    contractor: mockContractors[0],
    title: 'Apresentação de Proposta - Sistema CRM',
    description: 'Apresentação detalhada da proposta, demonstração de projetos anteriores e Q&A.',
    scheduledDate: '2024-11-22',
    startTime: '10:00',
    endTime: '11:30',
    duration: 90,
    location: 'Escritório - Sala de Reuniões 2',
    meetingLink: 'https://zoom.us/j/123456789',
    status: BookingStatus.SCHEDULED,
    attendees: ['João Silva', 'Pedro Costa', 'Equipe TechServ'],
    createdBy: '1',
    createdAt: '2024-11-16T16:30:00',
    updatedAt: '2024-11-16T16:30:00',
  },
  {
    id: '3',
    serviceRequestId: '3',
    proposalId: '4',
    contractorId: '2',
    contractor: mockContractors[1],
    title: 'Workshop - Arquitetura AWS',
    description: 'Workshop técnico para discutir a arquitetura proposta, revisar infraestrutura atual e planejar a migração.',
    scheduledDate: '2024-11-28',
    startTime: '09:00',
    endTime: '12:00',
    duration: 180,
    location: 'BuildPro Escritório - Av. Paulista',
    status: BookingStatus.SCHEDULED,
    attendees: ['Maria Santos', 'Equipe de TI', 'Arquitetos AWS da BuildPro'],
    notes: 'Trazer documentação da infraestrutura atual. Será fornecido café da manhã.',
    createdBy: '2',
    createdAt: '2024-11-15T10:00:00',
    updatedAt: '2024-11-15T10:00:00',
  },
  {
    id: '4',
    contractorId: '1',
    contractor: mockContractors[0],
    title: 'Consulta Inicial - Novo Projeto',
    description: 'Reunião exploratória para discutir necessidades e possíveis soluções.',
    scheduledDate: '2024-11-20',
    startTime: '15:00',
    endTime: '16:00',
    duration: 60,
    meetingLink: 'https://meet.google.com/xyz-abcd-efg',
    status: BookingStatus.COMPLETED,
    attendees: ['João Silva', 'Consultor TechServ'],
    notes: 'Reunião produtiva. Será enviada proposta formal em 3 dias úteis.',
    createdBy: '1',
    createdAt: '2024-11-18T14:00:00',
    updatedAt: '2024-11-20T16:05:00',
  },
];

export { mockServiceRequests, mockServiceProposals, mockServiceBookings };

export interface MockJob {
  id: string;
  title: string;
  department: string;
  location: string;
  type: string;
  status: string;
  description: string;
  requirements: string[];
  postedAt: string;
  closedAt?: string;
}

export interface MockCandidate {
  id: string;
  name: string;
  email: string;
  phone?: string;
  resume?: string;
  status: string;
  appliedAt: string;
  jobId: string;
}

export interface MockApplication {
  id: string;
  candidateId: string;
  jobId: string;
  status: string;
  appliedAt: string;
  notes?: string;
}

export const mockJobs: MockJob[] = [
  {
    id: '1',
    title: 'Senior Frontend Developer',
    department: 'Engenharia',
    location: 'Remoto',
    type: 'Tempo Integral',
    status: 'OPEN',
    description: 'Estamos procurando um desenvolvedor frontend sênior para se juntar à nossa equipe. Você trabalhará com tecnologias modernas como React, TypeScript e Next.js, desenvolvendo interfaces de usuário de alta qualidade.',
    requirements: [
      '5+ anos de experiência com React',
      'Conhecimento sólido de TypeScript',
      'Experiência com gerenciamento de estado (Redux, Zustand)',
      'Conhecimento de testes (Jest, React Testing Library)',
      'Experiência com CI/CD',
    ],
    postedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    title: 'Product Manager',
    department: 'Produto',
    location: 'São Paulo - SP',
    type: 'Tempo Integral',
    status: 'OPEN',
    description: 'Procuramos um Product Manager experiente para liderar o desenvolvimento de produtos inovadores. Você será responsável por definir a visão do produto, priorizar features e trabalhar com equipes multidisciplinares.',
    requirements: [
      '3+ anos de experiência como Product Manager',
      'Experiência com metodologias ágeis',
      'Habilidades analíticas e de comunicação',
      'Experiência com ferramentas de produto (Jira, Figma)',
    ],
    postedAt: '2024-01-20T14:30:00Z',
  },
  {
    id: '3',
    title: 'UX Designer',
    department: 'Design',
    location: 'Rio de Janeiro - RJ',
    type: 'Tempo Integral',
    status: 'OPEN',
    description: 'Buscamos um UX Designer criativo e orientado por dados para criar experiências de usuário excepcionais. Você trabalhará em estreita colaboração com desenvolvedores e product managers.',
    requirements: [
      '4+ anos de experiência em UX Design',
      'Portfólio demonstrando processos de design thinking',
      'Proficiência em Figma, Sketch ou Adobe XD',
      'Experiência com pesquisa de usuários',
    ],
    postedAt: '2024-01-10T09:00:00Z',
  },
  {
    id: '4',
    title: 'HR Specialist',
    department: 'Recursos Humanos',
    location: 'Brasília - DF',
    type: 'Tempo Integral',
    status: 'DRAFT',
    description: 'Vaga em processo de criação...',
    requirements: [],
    postedAt: '2024-02-01T08:00:00Z',
  },
  {
    id: '5',
    title: 'Backend Developer',
    department: 'Engenharia',
    location: 'Remoto',
    type: 'Tempo Integral',
    status: 'OPEN',
    description: 'Procuramos um desenvolvedor backend para trabalhar com Node.js, Python ou Go. Você será responsável por desenvolver APIs robustas e escaláveis.',
    requirements: [
      '4+ anos de experiência em desenvolvimento backend',
      'Conhecimento de Node.js, Python ou Go',
      'Experiência com bancos de dados (PostgreSQL, MongoDB)',
      'Conhecimento de arquitetura de microsserviços',
    ],
    postedAt: '2024-01-25T11:00:00Z',
  },
];

export const mockCandidates: MockCandidate[] = [
  {
    id: '1',
    name: 'João Silva',
    email: 'joao.silva@example.com',
    phone: '+55 11 99999-9999',
    jobId: '1',
    status: 'INTERVIEW',
    appliedAt: '2024-01-20T14:30:00Z',
  },
  {
    id: '2',
    name: 'Maria Santos',
    email: 'maria.santos@example.com',
    phone: '+55 21 88888-8888',
    jobId: '2',
    status: 'SCREENING',
    appliedAt: '2024-01-22T10:15:00Z',
  },
  {
    id: '3',
    name: 'Pedro Oliveira',
    email: 'pedro.oliveira@example.com',
    phone: '+55 11 77777-7777',
    jobId: '1',
    status: 'NEW',
    appliedAt: '2024-01-28T16:45:00Z',
  },
  {
    id: '4',
    name: 'Ana Costa',
    email: 'ana.costa@example.com',
    phone: '+55 21 66666-6666',
    jobId: '3',
    status: 'OFFER',
    appliedAt: '2024-01-15T09:30:00Z',
  },
  {
    id: '5',
    name: 'Carlos Ferreira',
    email: 'carlos.ferreira@example.com',
    jobId: '5',
    status: 'HIRED',
    appliedAt: '2024-01-12T08:00:00Z',
  },
  {
    id: '6',
    name: 'Juliana Alves',
    email: 'juliana.alves@example.com',
    phone: '+55 11 55555-5555',
    jobId: '1',
    status: 'REJECTED',
    appliedAt: '2024-01-18T13:20:00Z',
  },
];

export const mockApplications: MockApplication[] = [
  {
    id: '1',
    candidateId: '1',
    jobId: '1',
    status: 'UNDER_REVIEW',
    appliedAt: '2024-01-20T14:30:00Z',
    notes: 'Candidato com perfil forte, agendar entrevista técnica',
  },
  {
    id: '2',
    candidateId: '2',
    jobId: '2',
    status: 'PENDING',
    appliedAt: '2024-01-22T10:15:00Z',
  },
  {
    id: '3',
    candidateId: '3',
    jobId: '1',
    status: 'PENDING',
    appliedAt: '2024-01-28T16:45:00Z',
  },
  {
    id: '4',
    candidateId: '4',
    jobId: '3',
    status: 'INTERVIEW',
    appliedAt: '2024-01-15T09:30:00Z',
    notes: 'Segunda rodada de entrevistas agendada',
  },
];

